## Actividad: Obtención de estadísticas descriptivas

### Osmar Araico Gonzalez-A01664590
### Jose Luis Almeida Esparza-A01028493

### 1.Carga de datos con pandas

In [2]:
import pandas as pd

df = pd.read_csv('/content/avocado.csv')

In [10]:
#Verificamos contenido del dataset
df.shape

(18249, 13)

In [9]:
#Revisamos las columnas y hacemos
df.columns

Index(['Date', 'AveragePrice', 'Total Volume', '4046', '4225', '4770',
       'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year',
       'region'],
      dtype='object')

In [28]:
#Revisamos que valores contienen las columnas
df.dtypes

Date             object
AveragePrice    float64
Total Volume    float64
4046            float64
4225            float64
4770            float64
Total Bags      float64
Small Bags      float64
Large Bags      float64
XLarge Bags     float64
type             object
year              int64
region           object
dtype: object

In [11]:
#Aseguramos que las columnas no contegan valores nulos con df.dropna
df = df[
    [
        'Date', 'AveragePrice', 'Total Volume', '4046', '4225',
       '4770', 'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type',
       'year', 'region']
    ]
df.dropna()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [31]:
#Analizar las variables para saber que representan y sus rangos
print(df.describe())

print(f"La mediana de los datos son: \n{df.median()}")

       AveragePrice  Total Volume          4046          4225          4770  \
count  18249.000000  1.824900e+04  1.824900e+04  1.824900e+04  1.824900e+04
mean       1.405978  8.506440e+05  2.930084e+05  2.951546e+05  2.283974e+04
std        0.402677  3.453545e+06  1.264989e+06  1.204120e+06  1.074641e+05
min        0.440000  8.456000e+01  0.000000e+00  0.000000e+00  0.000000e+00
25%        1.100000  1.083858e+04  8.540700e+02  3.008780e+03  0.000000e+00
50%        1.370000  1.073768e+05  8.645300e+03  2.906102e+04  1.849900e+02
75%        1.660000  4.329623e+05  1.110202e+05  1.502069e+05  6.243420e+03
max        3.250000  6.250565e+07  2.274362e+07  2.047057e+07  2.546439e+06

         Total Bags    Small Bags    Large Bags    XLarge Bags          year
count  1.824900e+04  1.824900e+04  1.824900e+04   18249.000000  18249.000000
mean   2.396392e+05  1.821947e+05  5.433809e+04    3106.426507   2016.147899
std    9.862424e+05  7.461785e+05  2.439660e+05   17692.894652      0.939938
min    0.000000e+00  0.000000e+00  0.000000e+00       0.000000   2015.000000
25%    5.088640e+03  2.849420e+03  1.274700e+02       0.000000   2015.000000
50%    3.974383e+04  2.636282e+04  2.647710e+03       0.000000   2016.000000
75%    1.107834e+05  8.333767e+04  2.202925e+04     132.500000   2017.000000
max    1.937313e+07  1.338459e+07  5.719097e+06  551693.650000   2018.000000
La mediana de los datos son:
AveragePrice         1.37
Total Volume    107376.76
4046              8645.30
4225             29061.02
4770               184.99
Total Bags       39743.83
Small Bags       26362.82
Large Bags        2647.71
XLarge Bags          0.00
year              2016.00
dtype: float64

<ipython-input-31-c43cf257fee4>:4: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(f"La mediana de los datos son: \n{df.median()}")

##Conclusión

###Análisis de Datos


Basándose en la media, mediana y desviación estándar de cada variable, que conclusiones puedes entregar de los datos.

Osmar Araico:

A partir de la mediana, media y desviación estándar, se deduce que el precio y año de los aguacates son estables, mientras que las transacciones y volúmenes son variables con tendencia a valores atípicos altos, indicando ocasionalmente transacciones grandes.

Jose Luis:

Basándonos en los resultados podemos observar que los precios de los aguacates son estables, pero hay variabilidad en cantidad vendida y tipos de empaque, sugiriendo diferentes hábitos de compra o eventos puntuales que afectan las ventas.